### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kartsims** [jczaplew/csv-express#4]
I switched to your fork because it seems to be maintained while the original is not. So thank you for that !

I think you could improve the user experience though by improving the documentation.

Two things I noticed :

- `res.csv([data] [, csvHeaders] [, responseHeaders] [, statusCode])` the `data` parameter should not be between brackets as it is required
- you didn't provide a full example with all parameters (I noticed because I was wondering if `responseHeaders` should be an object or an array)

Cheers

**Comment by jczaplew** [comment]
Glad this fork is working for you! I added some additional examples to the README. If there is anything else you think could use clarification let me know.

**Comment by kartsims** [comment]
Good work, thanks !

**Comment by kartsims** [comment]
Oh and publishing to NPM would update the README there as well

**Comment by jczaplew** [comment]
I'll push an update to NPM once #6 is fixed as well. Should in in the next day or so.
