### ISSUE TITLE
Using a deprecated res.send()

### ISSUE THREAD

**Issue by jmsbtlr111** [jczaplew/csv-express#5]
The current signature used here https://github.com/jczaplew/csv-express/blob/master/lib/csv-express.js#L100 is deprecated since Express 2.x

http://expressjs.com/2x/guide.html#res.send()
http://expressjs.com/en/3x/api.html#res.send
http://expressjs.com/en/4x/api.html#res.send

Current method signature is `res.send([body])`

**Comment by JmsBtlr111** [comment]
Whoops. I see you are actually using the `http.ServerResponse` Class!

**Comment by jczaplew** [comment]
Good catch! This also brought to my attention the fact that providing custom headers and a status code do not work in Express 3+ (#6)

**Comment by jczaplew** [comment]
Fixed in 1.2.0
